### ISSUE TITLE
requeriments.txt

### ISSUE THREAD

**Issue by nuk3sk4te** [Quantika14/osint-suite-tools#1]
Hola muy buena la tool

Gracias por compartirla

En el script BuscadorNick.py

Faltan en requeriments.txt añadir pyDNS y  validate_email

beautifulsoup4
wikipedia
requests
pyDNS
validate_email

**Comment by D4M0N1979** [comment]
Genial la tool.

Me da el siguiente error cuando intento ejecutar python BuscadorNick.py:

Traceback (most recent call last):
  File "BuscadorNick.py", line 35, in <module>
    from validate_email import validate_email
ImportError: No module named validate_email

La parte de buscador de personas me funciona perfectamente.
Gracias por compartir una herramienta como esta.

**Comment by Quantika14** [comment]
Lo añadimos, gracias.

**Comment by JosegitHub21** [comment]
Fabulosa tool
Hay un error:
BuscadorNick.py", line 32, in <module>
 from validate_email import validate_email
ModuleNotFoundError: No module named 'validate_email'

Gracias por compartir esta herramienta
