### ISSUE TITLE
Buscador de personas no funciona

### ISSUE THREAD

**Issue by Zeloin** [Quantika14/osint-suite-tools#4]
Buenas:

Ejecuto el buscador de personas y despues de darme la opción de reporte o no el programa finaliza sin dar error, si le pido reporte me genera un fichero.png pero solo con campos vacios.

Tengo python3 y todas las dependencias que se piden instaladas.

P.D: Por cierto que solo pasa cuando usas la opción uno, con las otras dos parece que va bien.

**Comment by Quantika14** [comment]
Solucionado en el último comint.
Ya puede usarlo con nuevas funcionalidades añadidas hoy.
Un saludo.

**Comment by Zeloin** [comment]
Gracias. Ya me va perfectamente. Muy buena herramienta!!

**Comment by Zeloin** [comment]
Gracias!! Ya me va perfectamente. Muy buena herramienta!!
