### ISSUE TITLE
Error requiriments.txt "pydns"para Python3

### ISSUE THREAD

**Issue by goretex34** [Quantika14/osint-suite-tools#9]
Acabo de instalar este paquete de herramientas de OSINT y hay un conflicto de la dependencia "pydns".
Si se usa python 3, tal y como se indica en el repositorio,  seguramente sea solo necesario el módulo py3DNS (ya incluido también en requiriments.txt)
Parece ser que "pydns" no está soportado por Python 3.

**Comment by miguelns21** [comment]
Si se elimina este requerimiento, parece funcionar bien.

**Comment by miguelmsa1** [comment]
Podéis cambiarlo por py3DNS que sí está soportado en python3

**Comment by goretex34** [comment]
Efectivamente, esa fue mi conclusión/sugerencia: que se elimine de los requerimientos "pdns" (obsoleto) ya que el módulo "py3DNS ya está incluido en requiriments.txt.
